# Generated by Django 3.1.6 on 2021-02-02 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refrigerator',
            fields=[
                ('FID', models.CharField(max_length=52, primary_key=True, serialize=False)),
                ('IP', models.CharField(max_length=52)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UID', models.CharField(max_length=52, primary_key=True, serialize=False)),
                ('UNAME', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('FID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.refrigerator')),
            ],
        ),
    ]
